[book]
title = "Bot Designer For Discord - Wiki"
authors = ["NilPointer Software"]
description = "The official documentation of BDFD. It covers guides, examples related to BDScript, BDJS and as well features too."

[build]
create-missing = false

[output.html]
theme = "src/theme"
default-theme = "bdfd"
preferred-dark-theme = "bdfd"
smart-punctuation = true
git-repository-url = "https://github.com/NilPointer-Software/bdfd-wiki"
edit-url-template = "https://github.com/NilPointer-Software/bdfd-wiki/edit/dev/{path}"

[output.html.fold]
enable = true

[output.html.code]
hidelines = { bdscript = "{$hide}" }

[output.html.search]
boost-title = 4  

[preprocessor.mdbook-discord-components]
after = ["links"]
command = "mdbook-discord-components"
embed-script = false

[preprocessor.admonish]
on_failure = "bail"

# Redirects old wiki URL paths used by the app to new ones.
# TODO: Remove URLs when old paths gets updated in the app.
[output.html.redirect]
"/guides/ifStatements.html" = "./general/ifStatements.html"
"/guides/async.html" = "./general/bds2/asyncScopes.html"
"/guides/buttons.html" = "./general/interactions/buttons/aboutButtons.html"
"/selectmenu.html" = "./guides/general/interactions/selectMenus/aboutSelectMenu.html"
"/trycatch.html" = "./guides/general/bds2/errorHandling.html"

"/bdscript/awaitReactions.html" = "../premium/awaitReactions.html"
"/bdscript/customImage.html" = "../premium/customImage.html"
"/bdscript/ignoreTriggerCase.html" = "../premium/ignoreTriggerCase.html"

"/bdscript/httpAddHeader.html" = "../guides/general/httpRequests.html"
"/bdscript/httpDelete.html" = "../guides/general/httpRequests.html"
"/bdscript/httpGet.html" = "../guides/general/httpRequests.html"
"/bdscript/httpGetHeader.html" = "../guides/general/httpRequests.html"
"/bdscript/httpPatch.html" = "../guides/general/httpRequests.html"
"/bdscript/httpPost.html" = "../guides/general/httpRequests.html"
"/bdscript/httpPut.html" = "../guides/general/httpRequests.html"
"/bdscript/httpRemoveHeader.html" = "../guides/general/httpRequests.html"
"/bdscript/httpResult.html" = "../guides/general/httpRequests.html"
"/bdscript/httpResultComplex.html" = "../guides/general/httpRequests.html"
"/bdscript/httpStatus.html" = "../guides/general/httpRequests.html"

"/bdscript/json.html" = "../guides/general/jsonFunctions.html#json"
"/bdscript/jsonArray.html" = "../guides/general/jsonFunctions.html#jsonarray"
"/bdscript/jsonArrayAppend.html" = "../guides/general/jsonFunctions.html#jsonarrayappend"
"/bdscript/jsonArrayCount.html" = "../guides/general/jsonFunctions.html#jsonarraycount"
"/bdscript/jsonArrayIndex.html" = "../guides/general/jsonFunctions.html#jsonarrayindex"
"/bdscript/jsonArrayPop.html" = "../guides/general/jsonFunctions.html#jsonarraypop"
"/bdscript/jsonArrayReverse.html" = "../guides/general/jsonFunctions.html#jsonarrayreverse"
"/bdscript/jsonArrayShift.html" = "../guides/general/jsonFunctions.html#jsonarrayshift"
"/bdscript/jsonArraySort.html" = "../guides/general/jsonFunctions.html#jsonarraysort"
"/bdscript/jsonArrayUnshift.html" = "../guides/general/jsonFunctions.html#jsonarrayunshift"
"/bdscript/jsonClear.html" = "../guides/general/jsonFunctions.html#jsonclear"
"/bdscript/jsonExists.html" = "../guides/general/jsonFunctions.html#jsonexists"
"/bdscript/jsonJoinArray.html" = "../guides/general/jsonFunctions.html#jsonjoinarray"
"/bdscript/jsonParse.html" = "../guides/general/jsonFunctions.html#jsonparse"
"/bdscript/jsonPretty.html" = "../guides/general/jsonFunctions.html#jsonpretty"
"/bdscript/jsonSet.html" = "../guides/general/jsonFunctions.html#jsonset"
"/bdscript/jsonSetString.html" = "../guides/general/jsonFunctions.html#jsonsetstring"
"/bdscript/jsonStringify.html" = "../guides/general/jsonFunctions.html#jsonstringify"
"/bdscript/jsonUnset.html" = "../guides/general/jsonFunctions.html#jsonunset"

"/bdscript/webhookAvatarURL.html" = "../guides/general/webhooks.html"
"/bdscript/webhookColor.html" = "../guides/general/webhooks.html"
"/bdscript/webhookContent.html" = "../guides/general/webhooks.html"
"/bdscript/webhookCreate.html" = "../guides/general/webhooks.html"
"/bdscript/webhookDelete.html" = "../guides/general/webhooks.html"
"/bdscript/webhookDescription.html" = "../guides/general/webhooks.html"
"/bdscript/webhookFooter.html" = "../guides/general/webhooks.html"
"/bdscript/webhookSend.html" = "../guides/general/webhooks.html"
"/bdscript/webhookTitle.html" = "../guides/general/webhooks.html"
"/bdscript/webhookUsername.html" = "../guides/general/webhooks.html"
